[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.filesystem = littlefs
upload_port = COM3
monitor_port = COM3

lib_deps =
  bblanchon/ArduinoJson @ ^7
  me-no-dev/ESPAsyncWebServer @ ^1.2.3
  DNSServer
  BluetoothSerial
  ESP32 BLE Arduino

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DCONFIG_ARDUHAL_LOG_COLORS
